#!/usr/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [ ! "$(cat "$COMMIT_MSG_FILE" | head -n 1)" = '' ]; then
    exit 0
fi

msgOrig="$(cat "$COMMIT_MSG_FILE" | grep '^.\+')"
gitStatus="$(git status --porcelain --verbose --untracked-files=no  | sed 's|^\([A-Z]\)\([A-Z]\)\?\s\+|\1 |g')"
template='TYPE(SCOPE): DESC

#BODY

%s
#
#
#
%s'

printf "$template" "$gitStatus" "$msgOrig" > "$COMMIT_MSG_FILE"
